In [10]:
import utils, os
import numpy as np
import pandas as pd
import torch
from sklearn.preprocessing import StandardScaler

In [3]:
DATA_PATH = "../data/{}_data".format('rocksdb')
knobs_path = os.path.join(DATA_PATH, "configs")

In [4]:
from knobs import load_knobs
knob_data = load_knobs(knobs_path, 'rocksdb')
config = knob_data['data']

In [5]:
from metrics import load_metrics

In [7]:
target_external = "SCORE"
wk_internal_metrics_path = os.path.join(DATA_PATH, 'results', 'internal')
wk_external_metrics_path = os.path.join(DATA_PATH, 'results', 'external')
wk_internal_metrics_data = []
wk_external_metrics_data = []
# for wk in range(len(os.listdir(wk_internal_metrics_path))):
#     wk_internal_metric, _ = load_metrics(m_path = os.path.join(wk_internal_metrics_path, "internal_results_"+str(wk)+".csv"),
#                                             labels = knob_data['rowlabels'],
#                                             mode = 'internal')
#     wk_internal_metrics_data.append(wk_internal_metric)

for wk in range(len(os.listdir(wk_external_metrics_path))):
    wk_external_metric, _ = load_metrics(m_path = os.path.join(wk_external_metrics_path, "external_results_"+str(wk)+".csv"),
                                            labels = knob_data['rowlabels'],
                                            metrics = target_external,
                                            mode = 'external')
    wk_external_metrics_data.append(wk_external_metric)   

In [9]:
a = pd.read_csv(os.path.join(wk_external_metrics_path, "external_results_"+str(0)+".csv"), index_col=0)

In [25]:
default_ex = [20.7, 5.02, 10.9, 56.84]
b = [0.25, 0.25, 0.25, 0.25]

In [ ]:
[h_ex[0]/self.de_ex[0], self.de_ex[1]/h_ex[1], h_ex[2]/self.de_ex[2], h_ex[3]/self.de_ex[3]]

In [27]:
h = torch.rand(4, 32)
h, default_ex

(tensor([[0.7097, 0.5811, 0.2594, 0.7094, 0.7935, 0.3672, 0.6155, 0.2812, 0.0578,
          0.1317, 0.8501, 0.7587, 0.6929, 0.0497, 0.8091, 0.4869, 0.6307, 0.0776,
          0.2971, 0.1181, 0.4993, 0.2571, 0.4622, 0.3018, 0.0252, 0.7627, 0.9270,
          0.8221, 0.8076, 0.4413, 0.4653, 0.4317],
         [0.5849, 0.7895, 0.0841, 0.0945, 0.8664, 0.4719, 0.4411, 0.2581, 0.8643,
          0.5547, 0.6487, 0.0890, 0.7922, 0.8706, 0.5173, 0.9234, 0.7294, 0.5826,
          0.3743, 0.8553, 0.8380, 0.6946, 0.5820, 0.2279, 0.6766, 0.3815, 0.9925,
          0.5515, 0.4580, 0.8421, 0.3116, 0.2892],
         [0.1062, 0.8265, 0.7498, 0.7259, 0.3986, 0.1533, 0.3342, 0.1951, 0.5023,
          0.1128, 0.7317, 0.2226, 0.3465, 0.8254, 0.5997, 0.7927, 0.4282, 0.8508,
          0.3236, 0.3910, 0.3462, 0.8495, 0.6000, 0.9255, 0.2183, 0.2843, 0.8103,
          0.6583, 0.1250, 0.0709, 0.3949, 0.4558],
         [0.5878, 0.4322, 0.5519, 0.5717, 0.6654, 0.2722, 0.7929, 0.4676, 0.7604,
          0.2016, 0.5931, 0

In [36]:
d_h = [h[0]/default_ex[0], default_ex[1]/h[1], h[2]/default_ex[2], h[3]/default_ex[3]]
d_h

[tensor([0.0343, 0.0281, 0.0125, 0.0343, 0.0383, 0.0177, 0.0297, 0.0136, 0.0028,
         0.0064, 0.0411, 0.0367, 0.0335, 0.0024, 0.0391, 0.0235, 0.0305, 0.0038,
         0.0144, 0.0057, 0.0241, 0.0124, 0.0223, 0.0146, 0.0012, 0.0368, 0.0448,
         0.0397, 0.0390, 0.0213, 0.0225, 0.0209]),
 tensor([ 8.5833,  6.3581, 59.7238, 53.1469,  5.7941, 10.6375, 11.3819, 19.4502,
          5.8083,  9.0501,  7.7386, 56.3838,  6.3367,  5.7662,  9.7044,  5.4367,
          6.8820,  8.6173, 13.4109,  5.8696,  5.9908,  7.2273,  8.6251, 22.0303,
          7.4198, 13.1602,  5.0580,  9.1023, 10.9611,  5.9609, 16.1103, 17.3557]),
 tensor([0.0097, 0.0758, 0.0688, 0.0666, 0.0366, 0.0141, 0.0307, 0.0179, 0.0461,
         0.0103, 0.0671, 0.0204, 0.0318, 0.0757, 0.0550, 0.0727, 0.0393, 0.0781,
         0.0297, 0.0359, 0.0318, 0.0779, 0.0550, 0.0849, 0.0200, 0.0261, 0.0743,
         0.0604, 0.0115, 0.0065, 0.0362, 0.0418]),
 tensor([0.0103, 0.0076, 0.0097, 0.0101, 0.0117, 0.0048, 0.0140, 0.0082, 0.0134,
     

In [41]:
sum([_*b[i] for i, _ in enumerate(d_h)])

tensor([ 2.1594,  1.6174, 14.9537, 13.3145,  1.4702,  2.6685,  2.8641,  4.8725,
         1.4676,  2.2676,  1.9643, 14.1113,  1.6046,  1.4621,  2.4537,  1.3848,
         1.7421,  2.1765,  3.3674,  1.4788,  1.5150,  1.8301,  2.1777,  5.5361,
         1.8639,  3.3064,  1.2962,  2.3033,  2.7556,  1.5015,  4.0466,  4.3589])

In [14]:
a['SCORE'] = default_ex[0]/a['TIME']*0.25+a['RATE']/default_ex[1]*0.25+default_ex[0]/a['WAF']*0.25+default_ex[0]/a['SA']*0.25
a

TIME  RATE   WAF     SA  \
index                                                                          
/home/jieun/data_generation_rocksdb/rocksdb_con...   21.8  4.77   8.7  72.17   
/home/jieun/data_generation_rocksdb/rocksdb_con...   25.9  4.02   8.9  55.83   
/home/jieun/data_generation_rocksdb/rocksdb_con...   52.0  2.00   7.5  34.21   
/home/jieun/data_generation_rocksdb/rocksdb_con...   53.6  1.94  10.5  56.94   
/home/jieun/data_generation_rocksdb/rocksdb_con...   20.7  5.02  11.6  98.79   
...                                                   ...   ...   ...    ...   
/home/jieun/data_generation_rocksdb/rocksdb_con...  107.0  0.97  10.0  77.60   
/home/jieun/data_generation_rocksdb/rocksdb_con...   41.3  2.52   6.2  73.62   
/home/jieun/data_generation_rocksdb/rocksdb_con...   25.9  4.02   8.9  98.40   
/home/jieun/data_generation_rocksdb/rocksdb_con...   31.4  3.31   8.7  81.18   
/home/jieun/data_generation_rocksdb/rocksdb_con...   33.1  3.14   7.5  98.43   

                                                       SCORE  
index                                                         
/home/jieun/data_generation_rocksdb/rocksdb_con...  1.141468  
/home/jieun/data_generation_rocksdb/rocksdb_con...  1.074159  
/home/jieun/data_generation_rocksdb/rocksdb_con...  1.040392  
/home/jieun/data_generation_rocksdb/rocksdb_con...  0.776904  
/home/jieun/data_generation_rocksdb/rocksdb_con...  0.998505  
...                                                      ...  
/home/jieun/data_generation_rocksdb/rocksdb_con...  0.680859  
/home/jieun/data_generation_rocksdb/rocksdb_con...  1.155771  
/home/jieun/data_generation_rocksdb/rocksdb_con...  1.034058  
/home/jieun/data_generation_rocksdb/rocksdb_con...  0.988224  
/home/jieun/data_generation_rocksdb/rocksdb_con...  1.055294  

[20000 rows x 5 columns]

In [15]:
np.argmax(a['SCORE']), max(a['SCORE'])

(7367, 3.179063345955912)

In [7]:
wk_external_metric

{'columnlabels': array(['TIME', 'RATE', 'WAF', 'SA'], dtype=object),
 'rowlabels': array([    1,     2,     3, ..., 19998, 19999, 20000]),
 'data': array([[ 82.000,  12.490,  6.500,  466.980],
        [ 77.400,  13.230,  6.300,  356.740],
        [ 100.600,  10.190,  8.100,  206.590],
        ...,
        [ 127.500,  8.030,  5.800,  648.070],
        [ 118.600,  8.640,  6.500,  531.290],
        [ 146.900,  6.970,  6.600,  648.010]])}

In [6]:
wk_external_metrics_data

[{'columnlabels': array(['WAF'], dtype=object),
  'rowlabels': array([    1,     2,     3, ..., 19998, 19999, 20000]),
  'data': array([[ 8.700],
         [ 8.900],
         [ 7.500],
         ...,
         [ 8.900],
         [ 8.700],
         [ 7.500]])},
 {'columnlabels': array(['WAF'], dtype=object),
  'rowlabels': array([    1,     2,     3, ..., 19998, 19999, 20000]),
  'data': array([[ 8.800],
         [ 8.900],
         [ 7.200],
         ...,
         [ 8.800],
         [ 8.200],
         [ 6.500]])},
 {'columnlabels': array(['WAF'], dtype=object),
  'rowlabels': array([    1,     2,     3, ..., 19998, 19999, 20000]),
  'data': array([[ 6.000],
         [ 7.300],
         [ 6.700],
         ...,
         [ 6.700],
         [ 6.700],
         [ 4.900]])},
 {'columnlabels': array(['WAF'], dtype=object),
  'rowlabels': array([    1,     2,     3, ..., 19998, 19999, 20000]),
  'data': array([[ 6.100],
         [ 5.600],
         [ 6.900],
         ...,
         [ 6.000],
         

In [6]:
wk_stats_list = []
drop_columns = ['count', 'min', 'max']

for wk_internal_metric in wk_internal_metrics:
    wk_stats = wk_internal_metric.describe().T.drop(columns=drop_columns)
    wk_stats_list.append(wk_stats.T)

NameError: name 'wk_internal_metrics' is not defined

In [7]:
pruned_metrics = ['rocksdb.number.keys.written COUNT', 'rocksdb.block.cache.bytes.read COUNT', 'rocksdb.block.cache.data.bytes.insert COUNT', 'rocksdb.bytes.decompressed_SUM', 'rocksdb.block.cache.bytes.write COUNT', 'rocksdb.block.cache.index.bytes.insert COUNT', 'rocksdb.compact.read.bytes COUNT', 'rocksdb.bytes.compressed_SUM', 'rocksdb.compaction.times.micros_SUM', 'rocksdb.flush.write.bytes COUNT', 'rocksdb.bytes.read COUNT', 'rocksdb.compact.write.bytes COUNT', 'rocksdb.bytes.written COUNT', 'rocksdb.compaction.outfile.sync.micros_SUM', 'rocksdb.db.get.micros_SUM', 'rocksdb.db.flush.micros_SUM', 'rocksdb.compaction.times.cpu_micros_SUM', 'rocksdb.write.raw.block.micros_SUM', 'rocksdb.db.write.stall_SUM', 'rocksdb.read.block.get.micros_SUM']
metric_idxs = [i for i, metric_name in enumerate(wk_internal_metrics_data[0]['columnlabels']) if metric_name in pruned_metrics]

In [8]:
wk_pruned_internal_metrics_data = []
for wk_int_met in wk_internal_metrics_data:
    wk_int_met['data'] = wk_int_met['data'][:,metric_idxs]
    wk_pruned_internal_metrics_data.append(wk_int_met)

In [9]:
def numpy_to_df(numpy_):
    return pd.DataFrame(numpy_)

In [10]:
wk_stats_list = []
drop_columns = ['count', 'min', 'max']
target_wk = 15
target_size = 50

for i, wk_internal_metric in enumerate(wk_pruned_internal_metrics_data):
    df_wk_internal_metric = numpy_to_df(wk_internal_metric['data'])
    if i == target_wk:
        df_wk_internal_metric = df_wk_internal_metric.sample(target_size)
    wk_stats = df_wk_internal_metric.describe().T.drop(columns=drop_columns)
    wk_stats_list.append(wk_stats.T)

cov_internal_metrics = pd.concat(wk_stats_list, axis=1).T.cov()

In [11]:
int_idx = wk_stats_list[0].columns

In [12]:
from scipy.spatial import distance

In [15]:
# wk_mah_dis = []
wk_mah_dis = {}
for wk, wk_stats in enumerate(wk_stats_list):
    # if wk != target_wk:
    sum_d = 0
    for idx in int_idx:
        d = distance.mahalanobis(u=wk_stats[idx], v=wk_stats_list[target_wk][idx], VI=np.linalg.pinv(cov_internal_metrics))
        sum_d += d
    wk_mah_dis[wk] = sum_d

In [37]:
wk_mah_dis

{0: 41.46313352626349,
 1: 34.02466556035429,
 2: 33.572909243861744,
 3: 32.08183114685201,
 4: 38.22066171625489,
 5: 34.97549322532919,
 6: 31.366376533337927,
 7: 29.971842227695316,
 8: 44.64470287212374,
 9: 36.44898541940156,
 10: 32.74039449010933,
 11: 32.11533948742283,
 12: 62.67093208671621,
 13: 45.440422842173504,
 14: 30.689102725203956,
 15: 0.0}

In [42]:
sub_max_mah = {}
reverse_score = {}
for key in wk_mah_dis.keys():
    sub_max_mah[key] = max(wk_mah_dis.values()) - wk_mah_dis[key]
sub_max_mah.pop(target_wk) # remove target wk

for key in sub_max_mah.keys():
    reverse_score[key] = sub_max_mah[key]/sum(sub_max_mah.values())
wk_sorted_score = sorted(reverse_score.items(), key=(lambda x:x[1]), reverse=True) # return [(),(),()] list, tuple

In [18]:
sub_max_mah = max(wk_mah_dis) - wk_mah_dis
reverse_score = sub_max_mah/sum(sub_max_mah)
reverse_score

TypeError: unsupported operand type(s) for -: 'int' and 'dict'

In [235]:
wk_sorted_score = np.argsort(-reverse_score)
wk_sorted_score

array([0, 1, 2, 3])

In [69]:
wk_df_external_metrics = []
for wk_external_metric in wk_external_metrics_data:
    df_external_metric = pd.DataFrame(data=wk_external_metric['data'], columns=wk_external_metric['columnlabels'], index=wk_external_metric['rowlabels'])
    wk_df_external_metrics.append(df_external_metric)

In [77]:
sample_size = 20000
combined_wk = pd.DataFrame()
for _, (wk, score) in enumerate(wk_sorted_score):
    wk_sample_size = round(score * sample_size)
    # Sorting external metrics by workload
    sorted_df_external_metric = wk_df_external_metrics[wk].sort_values(by=['WAF'])
    # Remove duplicated index
    sorted_df_external_metric = sorted_df_external_metric.drop(combined_wk.index)
    print(f"{wk}th workload remained data size {len(sorted_df_external_metric)}, get data size {wk_sample_size}")
    
    combined_wk = pd.concat([combined_wk,sorted_df_external_metric[:wk_sample_size]])    

7th workload remained data size 20000, get data size 1723
14th workload remained data size 18277, get data size 1685
6th workload remained data size 16592, get data size 1649
3th workload remained data size 14943, get data size 1611
11th workload remained data size 13332, get data size 1610
10th workload remained data size 11722, get data size 1577
2th workload remained data size 10145, get data size 1533
1th workload remained data size 8612, get data size 1509
5th workload remained data size 7103, get data size 1459
9th workload remained data size 5644, get data size 1381
4th workload remained data size 4263, get data size 1288
0th workload remained data size 2975, get data size 1117
8th workload remained data size 1858, get data size 950
13th workload remained data size 908, get data size 908
12th workload remained data size 0, get data size 0


In [240]:
sample_size = 20000
combined_wk = pd.DataFrame()
for i, wk in enumerate(top_sort):
    wk_sample_size = round(reverse_score[i] * sample_size)
    # Sorting external metrics by workload
    sorted_df_external_metric = wk_df_external_metrics[wk].sort_values(by=['WAF'])
    # Remove duplicated index
    sorted_df_external_metric = sorted_df_external_metric.drop(combined_wk.index)
    print(f"{wk}th workload remained data size {len(sorted_df_external_metric)}, get data size {wk_sample_size}")
    
    combined_wk = pd.concat([combined_wk,sorted_df_external_metric[:wk_sample_size]])    

14th workload remained data size 20000, get data size 11571
7th workload remained data size 8429, get data size 6828
11th workload remained data size 1601, get data size 1601
10th workload remained data size 0, get data size 0


In [ ]:
sample_size = 20000
combined_wk = pd.DataFrame()
for wk in top_score:
    wk_sample_size = round(top_score[wk] * sample_size)
    # Sorting external metrics by workload
    sorted_df_external_metric = wk_df_external_metrics[wk].sort_values(by=['WAF'])
    # Remove duplicated index
    sorted_df_external_metric = sorted_df_external_metric.drop(combined_wk.index)
    print(f"{wk}th workload remained data size {len(sorted_df_external_metric)}, get data size {wk_sample_size}")
    
    combined_wk = pd.concat([combined_wk,sorted_df_external_metric[:wk_sample_size]])    

In [143]:
sample_size = 20000
wk_sample_size = int(sample_size/len(wk_score))
if wk_sample_size*len(wk_score) != sample_size: # if there is a remainder after division
    wk_sample_size = wk_sample_size + (sample_size- wk_sample_size*len(wk_score))
combined_wk = pd.DataFrame()

for wk in wk_score:
    # Sorting external metrics by workload
    sorted_df_external_metric = wk_df_external_metrics[wk].sort_values(by=['WAF'])
    # Remove duplicated index
    sorted_df_external_metric = sorted_df_external_metric.drop(combined_wk.index)
    print(f"{wk}th workload remained data size {len(sorted_df_external_metric)}")
    combined_wk = pd.concat([combined_wk,sorted_df_external_metric[:wk_sample_size]])
    wk_sample_size = int(sample_size/len(wk_score))

14th workload remained data size 20000
7th workload remained data size 18662
6th workload remained data size 17329
11th workload remained data size 15996
10th workload remained data size 14663
3th workload remained data size 13330
2th workload remained data size 11997
9th workload remained data size 10664
5th workload remained data size 9331
1th workload remained data size 7998
8th workload remained data size 6665
4th workload remained data size 5332
13th workload remained data size 3999
0th workload remained data size 2666
12th workload remained data size 1333


In [100]:
np.array(combined_wk)

NameError: name 'combined_wk' is not defined

In [214]:
combined_wk.index.is_unique

True

In [204]:
combined_wk.sort_index()

WAF
1       6.4
2       6.2
3       9.9
4      13.6
5       6.9
...     ...
19996   9.8
19997   6.3
19998   6.6
19999   6.7
20000   3.9

[20000 rows x 1 columns]

In [200]:
sorted_df_external_metric.drop(combined_wk.index)

WAF
2143    3.9
12321   4.1
8423    4.1
17124   4.1
11651   4.1
...     ...
18605  26.1
13489  27.3
2859   27.9
11329  29.0
14523  29.2

[20000 rows x 1 columns]

In [196]:
combined_wk.index

Int64Index([ 2143, 12321,  8423, 17124, 11651, 19929,  7922,   593,  6930,
             7185,
            ...
            13431,   355, 16799, 16783,  2377, 17525, 14671,  4025, 12628,
            10358],
           dtype='int64', length=1338)

In [173]:
f_wk_sample_size

1338

In [174]:
14*1333+1338

20000

In [165]:
wk_df_external_metrics[wk].sort_values(by=['WAF'])

WAF
2143    3.9
12321   4.1
8423    4.1
17124   4.1
11651   4.1
...     ...
18605  26.1
13489  27.3
2859   27.9
11329  29.0
14523  29.2

[20000 rows x 1 columns]

In [179]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error as MSE

In [241]:
combi_wk = pd.read_csv('combined_wk/210701_combined_wk_0.csv', index_col=0)
combi_wk.head()

WAF
1  8.2
2  7.2
3  7.2
4  8.5
5  7.5

In [242]:
target_wk = pd.read_csv('../data/rocksdb_data/results/external/external_results_0.csv')
target_waf = target_wk[['WAF']]
target_waf.head()

WAF
0   8.7
1   8.9
2   7.5
3  10.5
4  11.6

In [243]:
combi_wk = combi_wk.reset_index(drop=True)

In [244]:
(combi_wk[['WAF']] == target_waf[['WAF']]).value_counts()

WAF  
False    19139
True       861
dtype: int64

In [245]:
MSE(combi_wk['WAF'].values, target_waf['WAF'].values)

8.117584

In [247]:
for i in range(16):
    target_wk = pd.read_csv('../data/rocksdb_data/results/external/external_results_0.csv')
    train_wk = pd.read_csv(f'../data/rocksdb_data/results/external/external_results_{i}.csv')
    target_waf = target_wk[['WAF']]
    train_waf = train_wk[['WAF']]
    mse = MSE(train_waf['WAF'].values, target_waf['WAF'].values)
    print(f'{i+1} workload MSE: {mse}')
    num = (train_waf[['WAF']] == target_waf[['WAF']]).value_counts()
    # print(f'{i+1} workload same value numbers: \n{num}')

1 workload MSE: 0.0
2 workload MSE: 4.085368
3 workload MSE: 11.276116
4 workload MSE: 13.9992035
5 workload MSE: 7.179591499999999
6 workload MSE: 8.648807500000002
7 workload MSE: 12.523487
8 workload MSE: 14.043045999999999
9 workload MSE: 8.7440805
10 workload MSE: 11.7974105
11 workload MSE: 12.677317500000001
12 workload MSE: 12.993538
13 workload MSE: 14.198298000000001
14 workload MSE: 8.4011745
15 workload MSE: 9.860332000000001
16 workload MSE: 10.5773895
